repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: ["--all"]

  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        name: lint code with flake8
        additional_dependencies:
          - flake8-bugbear==23.2.13
          - flake8-comprehensions==3.10.1
          - flake8-simplify==0.19.3
          - flake8-docstrings==1.7.0
          - flake8-isort==6.0.0
          - flake8-black==0.3.6
          - flake8-bandit==4.1.1
        args:
          - --max-line-length=120
          - --docstring-convention=google
        exclude: ^tests
